UPDATE PATIENT
SET NAME = 'K', ADDRESS = 'RAJ'
WHERE NAME = 'A' AND ADDRESS = 'DHK';
UPDATE DOCTOR
SET DOCTOR.NAME = 'MS. Y' WHERE DOCTOR.NAME = 'MR. Y';
UPDATE APPOINTMENT_INFO
SET APPOINTMENT_INFO.D_NAME= 'MS. Y' WHERE APPOINTMENT_INFO.D_NAME= 'MR. Y';
DELETE FROM PATIENT WHERE PATIENT_NO = 'P-101';
DELETE FROM PATIENT;