CREATE TABLE INSTRUCTOR
(
    ID NUMBER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DEPT_NAME VARCHAR(50) NOT NULL,
    SALARY INT NOT NULL,
    CONSTRAINT PK_ID PRIMARY KEY (ID),
    CONSTRAINT SALARY_CHECK CHECK (SALARY>20000)
);