--TASK 1
SELECT ACT_FIRSTNAME|| ' ' || ACT_LASTNAME AS NAME FROM ACTOR, DIRECTOR WHERE ACT_FIRSTNAME=DIR_FIRSTNAME AND ACT_LASTNAME=DIR_LASTNAME;
SELECT ACT_FIRSTNAME || ' ' || ACT_LASTNAME AS NAME FROM ACTOR INTERSECT SELECT DIR_FIRSTNAME || ' ' || DIR_LASTNAME AS NAME FROM DIRECTOR;

--TASK 2
SELECT ACT_FIRSTNAME FROM ACTOR WHERE ACT_GENDER = 'F' GROUP BY ACT_FIRSTNAME HAVING COUNT(*)>1;

--TASK 3
SELECT ACT_LASTNAME|| ' ' || ACT_LASTNAME AS NAME FROM ACTOR UNION SELECT DIR_FIRSTNAME|| ' ' || DIR_LASTNAME FROM DIRECTOR;

--TASK 4
SELECT MOV_TITLE FROM MOVIE WHERE MOV_ID NOT IN (SELECT MOV_ID FROM RATING);

--TASK 5
SELECT AVG(REV_STARS) FROM RATING;

--TASK 6
SELECT MOV_TITLE, MIN(REV_STARS) AS MIN_RATE FROM RATING NATURAL JOIN MOVIE GROUP BY MOV_TITLE ORDER BY MIN_RATE DESC;

--TASK 7
SELECT MOV_TITLE FROM MOVIE WHERE MOV_ID IN(SELECT MOV_ID FROM RATING GROUP BY MOV_ID HAVING AVG(REV_STARS) > (SELECT AVG(REV_STARS) FROM RATING));

--TASK 8   
SELECT ACT_FIRSTNAME, ACT_LASTNAME, COUNT(*) AS number_of_ratings FROM ACTOR, CASTS, RATING WHERE ACTOR.ACT_ID = CASTS.ACT_ID AND CASTS.MOV_ID = RATING.MOV_ID 
GROUP BY ACT_FIRSTNAME , ACT_LASTNAME ORDER BY number_of_ratings DESC;

--TASK 9
SELECT DIR_FIRSTNAME,DIR_LASTNAME FROM DIRECTOR WHERE DIR_ID IN (SELECT DIR_ID FROM MOVIE JOIN RATING USING (MOV_ID) GROUP BY DIR_ID 
HAVING AVG(REV_STARS) = (SELECT MAX(AVG(REV_STARS)) FROM MOVIE JOIN RATING USING (MOV_ID) GROUP BY DIR_ID));

--TASK 10
SELECT *
FROM MOVIE 
WHERE MOV_ID
IN
(
    SELECT DN.MOV_ID
    FROM DIRECTION DN
    WHERE DN.DIR_ID
    IN
    (
        SELECT D.DIR_ID
        FROM DIRECTOR D
        WHERE D.DIR_FIRSTNAME || ' ' || D.DIR_LASTNAME
        IN
        (
            SELECT D1.DIR_FIRSTNAME || ' ' || D1.DIR_LASTNAME AS DIR_NAME1
            FROM DIRECTOR D1
            INTERSECT
            SELECT A.ACT_FIRSTNAME || ' ' || A.ACT_LASTNAME AS ACT_NAME
            FROM ACTOR A
        )
    )
);

--TASK 11
SELECT M.MOV_TITLE,
(
    SELECT avg(R.REV_STARS)
    FROM RATING R
    WHERE R.MOV_ID = M.MOV_ID
    AND R.REV_STARS IS NOT NULL
) AS AVG_RATE
FROM MOVIE M
WHERE M.MOV_ID
IN
(
    SELECT R1.MOV_ID
    FROM RATING R1
    WHERE R1.REV_STARS IS NOT NULL
    GROUP BY R1.MOV_ID
    HAVING avg(R1.REV_STARS) > 7
)
ORDER BY AVG_RATE DESC;

--TASK 12
SELECT R.REV_NAME
FROM REVIEWER R
WHERE R.REV_ID
IN
(
    SELECT RT.REV_ID
    FROM RATING RT
    WHERE RT.REV_STARS = 
    (
        SELECT min(REV_STARS)
        FROM RATING
    )
);

--TASK 13
SELECT A.ACT_FIRSTNAME || ' ' ||A.ACT_LASTNAME AS ACT_NAME,
(
    SELECT avg(M.MOV_TIME)
    FROM MOVIE M
    WHERE M.MOV_ID 
    IN
    (
        SELECT C.MOV_ID
        FROM CASTS C
        WHERE C.ACT_ID = A.ACT_ID
    )
    AND M.MOV_TIME IS NOT NULL
) AS AVG_RUNTIME
FROM ACTOR A
WHERE A.ACT_ID
IN
(
    SELECT ACT_ID FROM CASTS
)
AND A.ACT_ID 
NOT IN
(
    SELECT C2.ACT_ID
    FROM CASTS C2
    WHERE C2.MOV_ID
    IN
    (
        SELECT DN.MOV_ID
        FROM DIRECTION DN
        WHERE DN.DIR_ID =
        (
            SELECT DR.DIR_ID
            FROM DIRECTOR DR
            WHERE DR.DIR_FIRSTNAME = 'James' AND DR.DIR_LASTNAME = 'Cameron'
        )
    )
)
ORDER BY ACT_NAME;